import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers"; // Import the client component

export const metadata: Metadata = {
  title: "Senior Assassin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}